### ISSUE TITLE
Scroll with DPad/stick

### ISSUE THREAD

**Issue by bastiHST90** [safijari/steam-deck-battery-tracker#2]
Just a little suggestion. Would be nice to scroll down in the plugin with dpad or the stick to see the average power consumption. At the moment it only works with touch.

**Comment by safijari** [comment]
I don't know how to do that unfortunately. Seems to be a decky limitation.

**Comment by bastiHST90** [comment]
Hmm.. in playtime it works. Ok, I mean at the bottom are buttons, but scrolling the plugin still works. It's unfortunate. Because I really don't want to use the touchscreen for anything. 😅
